import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Navbar from '../../components/Navbar'
import Hero from '../../components/Hero'
import Search from '../../components/Search'
import TripCard from '../../components/TripCard'
import data from '../../src/data.json'
import { useState } from 'react'

export default function Home() {
  const [searchText, setSearchText] = useState('')
  return (
    <>
      <Head>
        <title>Vamos a la playa</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css"
        />
      </Head>
      <section className="section-header">
        <Navbar></Navbar>
        <Hero></Hero>
      </section>
      <section className="search">
        <div className="headingSearch">
          <h2>A donde deseas viajar?</h2>
        </div>
        <Search setText={setSearchText}></Search>
      </section>
      <section className="cards">
        <TripCard
          data={data.filter((trip) => {
            return trip.label.includes(searchText)
          })}
        ></TripCard>
      </section>
    </>
  )
}
